// Code generated by goctl. DO NOT EDIT.
package types

type Response struct {
	Code    int                    `json:"code"`
	Message string                 `json:"message"`
	Data    map[string]interface{} `json:"data:omitempty"`
}

type CreateUserRequest struct {
	Name     string `form:"username"`
	Password string `form:"password"`
}

type GetUserRequest struct {
	Name string `path:"name"`
}
