// Code generated by goctl. DO NOT EDIT!
// Source: rpc.proto

//go:generate mockgen -destination ./rpc_mock.go -package rpcclient -source $GOFILE

package rpcclient

import (
	"context"

	"rpc/rpc"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	Request  = rpc.Request
	Response = rpc.Response

	Rpc interface {
		Ping(ctx context.Context, in *Request) (*Response, error)
	}

	defaultRpc struct {
		cli zrpc.Client
	}
)

func NewRpc(cli zrpc.Client) Rpc {
	return &defaultRpc{
		cli: cli,
	}
}

func (m *defaultRpc) Ping(ctx context.Context, in *Request) (*Response, error) {
	client := rpc.NewRpcClient(m.cli.Conn())
	return client.Ping(ctx, in)
}
